server:
  debug: true
  host: "0.0.0.0"
  port: "8005"
publisher:
  protocol: amqp
  host: rabbitmq
  port: "5672"
  username: guest
  password: guest
memory_storage:
  host: redis
  port: "6379"
  key_prefix: "controllers"
api:
  protocol: http
  host: api
  port: "8000"